namespace Lizards.Mvctoolkit.Demo
{
  using Lizards.Mvctoolkit.Demo.Services;
  using Lizards.MvcToolkit.Core.Blocks;
  using Lizards.MvcToolkit.Core.Blocks.Defaults;
  using Microsoft.AspNetCore.Hosting;
  using Microsoft.Extensions.Configuration;

  /// <summary>
  ///
  /// </summary>
  /// <seealso cref="Lizards.MvcToolkit.Core.Blocks.Startup" />
  /// <autogeneratedoc />
  public sealed class DemoStartup : Startup
  {
    /// <summary>
    /// Initializes a new instance of the <see cref="DemoStartup"/> class.
    /// </summary>
    /// <param name="env">The env.</param>
    /// <param name="configuration">The configuration.</param>
    /// <autogeneratedoc />
    public DemoStartup(IHostingEnvironment env, IConfiguration configuration)
      : base(env, configuration)
    {
      this.ApplyDefault(new BasicAspNetBlock(this.ExceptionHandlingRoute));
      this.ApplyDefault(new CQRSBlock("Lizards.Mvctoolkit.Demo"));
      this.ApplyDefault<RegisterServiceBlock<IService, Service>>();
      this.ApplyDefault<HttpClientFactoryBlock>();
    }

    /// <summary>Gets the exception handling route.</summary>
    /// <value>The exception handling route.</value>
    /// <autogeneratedoc />
    private string ExceptionHandlingRoute => "/home/error";
  }
}
